/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts/index'
import { Route as ReceiptsActionRequiredRouteImport } from './routes/receipts/action-required'

const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsActionRequiredRoute = ReceiptsActionRequiredRouteImport.update({
  id: '/receipts/action-required',
  path: '/receipts/action-required',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRoute
  '/receipts/action-required': typeof ReceiptsActionRequiredRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRoute
  '/receipts/action-required': typeof ReceiptsActionRequiredRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRoute
  '/receipts/action-required': typeof ReceiptsActionRequiredRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/receipt' | '/receipts/action-required' | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/receipt' | '/receipts/action-required' | '/receipts'
  id: '__root__' | '/' | '/receipt' | '/receipts/action-required' | '/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiptRoute: typeof ReceiptRoute
  ReceiptsActionRequiredRoute: typeof ReceiptsActionRequiredRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/action-required': {
      id: '/receipts/action-required'
      path: '/receipts/action-required'
      fullPath: '/receipts/action-required'
      preLoaderRoute: typeof ReceiptsActionRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiptRoute: ReceiptRoute,
  ReceiptsActionRequiredRoute: ReceiptsActionRequiredRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
